#!/bin/bash
. scripts/_paths

ttf_directory="${build_directory}/ttf"

echo "Building TTF..."
fontmake -m $designspace_file -o ttf --output-dir $ttf_directory -i

statics=$(ls $ttf_directory/*.ttf)
for file in $statics; do 
    echo "Fixing DSIG in " ${file}
    gftools fix-dsig --autofix ${file}

    echo "Autohint" ${file}
    hintedFile=${file/".ttf"/"-hinted.ttf"}
    ttfautohint -I ${file} ${hintedFile} --stem-width-mode nnn --composites --windows-compatibility
    cp ${hintedFile} ${file}
    rm -rf ${hintedFile}
done

echo "TTF builded!"