#!/bin/bash
. scripts/_paths

vf_directory="${build_directory}/variable_ttf"
vf_file="${vf_directory}/Lilex-VF.ttf"

echo "Building variable TTF..."
фывfontmake -m $designspace_file -o variable --output-dir $vf_directory > /dev/null 2>&1

echo "Fixing meta..."
gftools fix-vf-meta $vf_file > /dev/null 2>&1
gftools fix-nonhinting $vf_file $vf_file > /dev/null 2>&1
gftools fix-gasp --autofix $vf_file > /dev/null 2>&1
gftools fix-dsig --autofix $vf_file > /dev/null 2>&1

temp_files=$(ls $vf_directory/*.fix && ls $vf_directory/*-gasp*)
for temp in $temp_files
do
    rm -rf $temp
done

echo "Variable TTF builded!"