name: Report Italic Progress

on:
  pull_request

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      download_url: true
  publish:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Bootstrap environment
      run: make configure

    - name: Download URL
      uses: actions/download-artifact@v4
      with:
        name: URL
        path: ./

    - name: Get progress
      run: |
        . venv/bin/activate
        python scripts/porting.py progress \
          --markdown \
          --download-url $(cat ./download_url.txt) > progress.md

    - name: Post progress
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: progress.md
